### PR TITLE
Extract Circuits Performance Improvement

### PR DESCRIPTION
**Pull request by bcdonovan**
This PR improves the performance of the ExtractCircuitsPass by replacing `insertArguments` with `getBody().addArugment`. 

Also fixes a bug by inserting call_circuit after location of last operation in circuit rather than the first.

### CODE REVIEW

**Review by taalexander — CHANGES_REQUESTED** [review]
This change looks good to me! I also found it necessary to update the way the circuit operations are being walked on my machine in https://github.com/bcdonovan/qe-compiler/pull/1. With this I get performance of 

`0.0676 (  0.1%)    0.0676 (  0.4%)            Extract Circuits Pass`

without this it was closer to 1 min 50s.

for 100x100x1 circuits.

**Review by taalexander — APPROVED** [review]
LGTM

**Review by mbhealy — APPROVED** [review]
LGTM

**Review by kitbarton — DISMISSED** [review]
LGTM.

**Review by kitbarton — DISMISSED** [review]

**Review by taalexander — APPROVED** [review]

**Pull request merged**
