### PR TITLE
search upward for parameters

### PR DESCRIPTION
**Pull request by bcdonovan**
This PR adjusts the ParameterInitialValueAnalysis so that it will search the current module for parameter definitions and then search parent modules if parameters are not found.

### CODE REVIEW

**Comment by mbhealy** [comment]
There doesn't appear to be an existing test that calls this pass directly. Do we have some test that exercises this code? If not can we add one in this repo?

**Review by kitbarton — DISMISSED** [review]
LGTM.

I agree with @mbhealy it would be good to have a test case, if it's easy to do.

**Comment by bcdonovan** [comment]
Added a test with: 48af563

**Review by mbhealy — APPROVED** [review]
LGTM

**Pull request merged**
